name: Maven build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Set up JDK 8
        uses: actions/setup-java@v4  # Use v4 instead of v5 for Java 8
        with:
          java-version: '8'
          distribution: 'temurin'
        
      - name: Build with Maven
        run: mvn -f com.example.progetto.angelo.rosa.test/pom.xml clean verify