name: Maven build

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  build:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: [17, 21]
        include:
          - os: ubuntu-latest
            java: 17
            # run PIT mutation test once along with integration tests, jacoco, e2e, coveralls and surefire report plugin generation on ubuntu
            maven-cmd: "mvn verify -f com.example.progetto.angelo.rosa.test/pom.xml surefire-report:report-only -DrepoToken=$COVERALLS_REPO_TOKEN coveralls:report -Pintegration-tests org.pitest:pitest-maven:mutationCoverage"
            integration-tests: with PIT and integration tests
          - java: 21
            # junit only for java 21 on ubuntu
            maven-cmd: "mvn test -f com.example.progetto.angelo.rosa.test/pom.xml"
          - os: windows-latest
            java: 17
            # junit only for java 17 on windows
            maven-cmd: "mvn test -f com.example.progetto.angelo.rosa.test/pom.xml"
        exclude:
          # skip java 21 on windows 
          - os: windows-latest
            java: 21

    name: Build with Java ${{ matrix.java }} on ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2
            ~/.sonar/cache
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
          restore-keys: ${{ runner.os }}-m2-
        
      - name: Build with Maven ${{ matrix.os }} on Java ${{ matrix.java }} ${{ matrix.integration-tests }}
        run: >
          ${{ matrix.maven-cmd }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

      - name: Archive JUnit Report
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.java == 17 }}
        uses: actions/upload-artifact@v4
        with:
          name: surefire-report-jdk-${{ matrix.java }}-${{ matrix.os }}
          path: '**/target/site/jacoco'