name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  build:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false

    runs-on: 'ubuntu-latest'

    name: SonarCloud
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: "temurin"

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2
            ~/.sonar/cache
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Build with Maven and SonarCloud
        # run integration test in order to let maven to create failsafe output in verify phase
        run: >
            xvfb-run mvn verify sonar:sonar -Pjacoco -Pintegration-tests
            -Dsonar.organization=virgula0
            -Dsonar.projectKey=Virgula0_JavaRepoTest
            -Dsonar.host.url=https://sonarcloud.io
        working-directory: com.example.progetto.angelo.rosa.test
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}